### ISSUE TITLE
I have no clue what zone data is

### ISSUE THREAD

**Issue by MXRepel** [Project-Sloth/ps-zones#1]
I have written 5 zones with different triggers and names but I have no idea what zone data is. When I walk into 1 zone it triggers all 5 at once even though the zones have different names. I have next to no experience in polyzone and I feel like Ive learned alot in this process but I cant find anything online for it! Please help as I was excited to do this project but at this point im bashing my head into a wall. I will attach all my files for what I have written
[ps-zones.zip](https://github.com/Project-Sloth/ps-zones/files/13062231/ps-zones.zip)

**Comment by MonkeyWhisper** [comment]
Script is no supported.
